---
title: "Third Data Viz"
description: |
  A short description of the post.
author:
  - name: Alejandra Garcia Isaza
    url: https://github.com/Alegarisa
date: 03-18-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


library(tidyverse)
library(rio)
library(here)
library(dplyr)
library(gghighlight)
library(patchwork)
library(gganimate)
library(ggplot2)
library(gifski)
library(colorblindr)

theme_set(theme_minimal(base_size = 15))

```

```{r}

d <- import(here("data", "alejandra-sim.csv"), setclass = "tbl_df") 

# editing names
d <- rename(d, treatment = c("group"), agew1 = c("md1age"), agew8 = c("md8age"), maltxrecs = c("total_number_maltx_records"), placechange = c("pre_b_lplacechanges"), severitymaltx = c("severitymn"), totcupsgain = c("cup_agrto"), totcupsloss = c("cup_alrto"))

```

First attempt

```{r, fig.height= 6, fig.width=8}

tidy_d2 <- d %>%
  gather(valence, number, 22:23)

tidy_d2 <- tidy_d2 %>%
  mutate(valence = factor(valence),
         family = factor(family))


ggplot(tidy_d2, aes(valence, number)) +
  geom_col() +
  facet_wrap(~ treatment)

```

Second attempt

```{r, fig.height= 6, fig.width=8}

d2 <- d %>%
  select(family, treatment, totcupsgain, totcupsloss) %>%
  group_by(treatment) %>%
  mutate(`Seek gains` = mean(totcupsgain, na.rm = TRUE),
         `Avoid losses` = mean(totcupsloss, na.rm = TRUE))

d2 <- d2 %>%
  gather(avg, value, -1:-4)

ggplot(d2, aes(avg, value)) +
  geom_col(fill = "cornflowerblue") + # I don't know why the y-axis goes until 750 if I already calculated the averages.
  facet_wrap(~ treatment) + 
  labs(title = "Average of Risky Choices made to Seek Gains and To avoid Losses by Treatment Condition",
       subtitle = "Decision Making Assessed with CUPS Task",
       y = "Average of Risky Choices",
       x = "")

```

Third version

```{r, fig.height= 6, fig.width=8}

tidy_d2 <- tidy_d2 %>%
  mutate(valence = fct_recode(valence,
                           "Avoid losses" = "totcupsloss",
                           "Seek gains" = "totcupsgain"))

ggplot(tidy_d2, aes(valence, number)) +
  geom_point(position = position_jitter(0.3), alpha = 0.4, color = "cornflowerblue", size = 2) + 
  stat_summary(fun.y = mean, geom = "point", color = "gray30") +
  stat_summary(fun.data = mean_sdl, geom = "errorbar", width = 0.2, col = "gray60") +
  facet_wrap(~ treatment) + 
  scale_y_continuous("Average of Risky Choices", limits = c(0, 40)) +
  labs(title = "Average of Risky Choices Made to Seek Gains and to Avoid Losses",
       subtitle = "Decision Making Assessed with CUPS Task",
       x = "") +
  theme(plot.title = element_text(family = "sans", size = 16, face = "bold", hjust = 0), 
        plot.subtitle = element_text(family = "sans", size = 14, face = "italic", hjust = 0,
                                     margin = margin(0, 0, 30, 0)),
        axis.text.x.bottom = element_text(family = "sans", size = 12),
        axis.title.y = element_text(family = "sans", size = 12, margin = margin(20, 20, 10, 10)))

```

